services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./index.html:/app/index.html
      - ./404.html:/app/404.html

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - server/.env
    restart: always
