services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000
    container_name: frontend2
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    networks:
      - stargaze-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend2
    env_file:
      - server/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/uprev_main_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stargaze-network

  db:
    image: pgvector/pgvector:pg17
    container_name: db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uprev_main_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - stargaze-network

volumes:
  pgdata:


networks:
  stargaze-network:
    external: true
